export const dataSlide = [
    {
      id:1,
      title:"My Portfolio",
      desc:"A project I'm proud of, clean code and 100% of my audit. My portfolio shows my current knowledge of the different features in the react library and Next.js framework. In my GitHub repository you can see the entire code and evaluate my knowledge. ",
      skills:"HTLM5, CSS3, JavaScript, React.js, Next.js, Tailwind",
      img:"/myPortfolioProject.png",
      url:"https://github.com/antonio-fmartins/DevAntonioMartins",
    },
    {
      id:2,
      title:"Landing Page - Indecor",
      desc:"Study project I did in the first steps in the programming area, a simple landing page made for a home decor company",
      skills:"HTLM5, CSS3",
      img:"/1project.png",
      url:"https://github.com/antonio-fmartins/LandingPage-1",
    },
    {
      id:3,
      title:"Landing Page - Adventure",
      desc:"Study project to deepen knowledge of the use of HTML5 and CSS3 with a short introduction to JavaScript used for the Mobile Navigation Menu. ",
      skills:"HTLM5, CSS3, JavaScript",
      img:"/2project.png",
      url:"https://github.com/antonio-fmartins/LandingPage-2",
    },
    {
      id:4,
      title:"Task List Project",
      desc:"I've done this project on my own, using the Vanilla JavaScript language. I've tried to make the most of my knowledge and put it into practice in this project, using APIs, functions, conditions and much more",
      skills:"HTLM5, CSS3, JavaScript",
      img:"/3project.png",
      url:"https://github.com/antonio-fmartins/Todo-App",
    },
    {
      id:5,
      title:"Weather App",
      desc:"Weather forecasting project where knowledge of Vanilla JavaScript was explored, with a focus on learning about APIs, promises and responsive design. ",
      skills:"HTLM5, CSS3, JavaScript",
      img:"/4project.png",
      url:"https://github.com/antonio-fmartins/Weather-App",
    },
    {
      id:6,
      title:"Todo React App",
      desc:"In this project I deepened my knowledge of ReactJS, using resources such as Hooks, destructuring, components and other techniques widely used in website development with this library.",
      skills:"HTLM5, CSS3, JavaScript, ReactJS",
      img:"/5project.png",
      url:"https://github.com/antonio-fmartins/Todo-App-React",
    },
  ]